@BASE = http://127.0.0.1:8080/api/v1

### All comments
GET {{BASE}}/comments

###

### Insertar un nuevo comentario
#commentId, userId, photoId, text, date 
POST {{BASE}}/comments
Content-Type: application/json

{
    "userId": 1,
    "photoId": 1,
    "text": "COMENTARIO A TRAVÉS DE http"
}


### Borrar un comentario
DELETE {{BASE}}/comments/4